//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAppClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stringStatistics", Namespace="http://schemas.datacontract.org/2004/07/A1Berrios_Sean_Part1")]
    [System.SerializableAttribute()]
    public partial class stringStatistics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int digitCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int lowerCaseCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int upperCaseCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int vowelCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int digitCount {
            get {
                return this.digitCountField;
            }
            set {
                if ((this.digitCountField.Equals(value) != true)) {
                    this.digitCountField = value;
                    this.RaisePropertyChanged("digitCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int lowerCaseCount {
            get {
                return this.lowerCaseCountField;
            }
            set {
                if ((this.lowerCaseCountField.Equals(value) != true)) {
                    this.lowerCaseCountField = value;
                    this.RaisePropertyChanged("lowerCaseCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int upperCaseCount {
            get {
                return this.upperCaseCountField;
            }
            set {
                if ((this.upperCaseCountField.Equals(value) != true)) {
                    this.upperCaseCountField = value;
                    this.RaisePropertyChanged("upperCaseCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vowelCount {
            get {
                return this.vowelCountField;
            }
            set {
                if ((this.vowelCountField.Equals(value) != true)) {
                    this.vowelCountField = value;
                    this.RaisePropertyChanged("vowelCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/wordCount", ReplyAction="http://tempuri.org/IService1/wordCountResponse")]
        int wordCount(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/wordCount", ReplyAction="http://tempuri.org/IService1/wordCountResponse")]
        System.Threading.Tasks.Task<int> wordCountAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/analyzeStr", ReplyAction="http://tempuri.org/IService1/analyzeStrResponse")]
        webAppClient.ServiceReference1.stringStatistics analyzeStr(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/analyzeStr", ReplyAction="http://tempuri.org/IService1/analyzeStrResponse")]
        System.Threading.Tasks.Task<webAppClient.ServiceReference1.stringStatistics> analyzeStrAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : webAppClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<webAppClient.ServiceReference1.IService1>, webAppClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int wordCount(string str) {
            return base.Channel.wordCount(str);
        }
        
        public System.Threading.Tasks.Task<int> wordCountAsync(string str) {
            return base.Channel.wordCountAsync(str);
        }
        
        public webAppClient.ServiceReference1.stringStatistics analyzeStr(string str) {
            return base.Channel.analyzeStr(str);
        }
        
        public System.Threading.Tasks.Task<webAppClient.ServiceReference1.stringStatistics> analyzeStrAsync(string str) {
            return base.Channel.analyzeStrAsync(str);
        }
    }
}
