//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a4_part_2_web_app.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verification", ReplyAction="http://tempuri.org/IService1/verificationResponse")]
        string verification(string xml, string xsd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verification", ReplyAction="http://tempuri.org/IService1/verificationResponse")]
        System.Threading.Tasks.Task<string> verificationAsync(string xml, string xsd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/xPathSearch", ReplyAction="http://tempuri.org/IService1/xPathSearchResponse")]
        string xPathSearch(string xml, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/xPathSearch", ReplyAction="http://tempuri.org/IService1/xPathSearchResponse")]
        System.Threading.Tasks.Task<string> xPathSearchAsync(string xml, string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : a4_part_2_web_app.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<a4_part_2_web_app.ServiceReference1.IService1>, a4_part_2_web_app.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string verification(string xml, string xsd) {
            return base.Channel.verification(xml, xsd);
        }
        
        public System.Threading.Tasks.Task<string> verificationAsync(string xml, string xsd) {
            return base.Channel.verificationAsync(xml, xsd);
        }
        
        public string xPathSearch(string xml, string path) {
            return base.Channel.xPathSearch(xml, path);
        }
        
        public System.Threading.Tasks.Task<string> xPathSearchAsync(string xml, string path) {
            return base.Channel.xPathSearchAsync(xml, path);
        }
    }
}
